version: "3.7"
services:
  express_mongo:
    container_name: express_mongo
    restart: always
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo/qrary
    networks:
      - express_mongo-network
    env_file: .env
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - express_mongo-network

volumes:
  mongo:
    name: mongo

networks:
  express_mongo-network:
    name: express_mongo-network
