version: "3"
services:
  app:
    container_name: express_mongo
    restart: always
    build: ./
    ports:
    - "8080:8080"
    volumes:
    - .:/app
    - .:/app/node_modules
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27017:27017"
